export enum ParticipantEvent {
  // PeerConnectionState
  Disconnected = 'disconnected',
  Connecting = 'connecting',
  Connected = 'connected',
  Failed = 'failed',
  New = 'new',
  Closed = 'closed',
  // ParticipantEvents
  Reconnecting = 'reconnecting',
  StateUpdate = 'stateUpdate',
  CursorUpdate = 'cursorUpdate',
  AudioStreamAdded = 'audioStreamAdded',
  AudioStreamRemoved = 'audioStreamRemoved',
  MuteToggled = 'muteToggled',
  CursorToggled = 'cursorToggled',
  TrackMuted = 'trackMuted',
  TrackUnmuted = 'trackUnmuted',
  LocalTrackPublished = 'localTrackPublished',
  LocalTrackUnpublished = 'localTrackUnpublished',
  ParticipantMetadataChanged = 'participantMetadataChanged',
  IsSpeakingChanged = 'isSpeakingChanged',
  ConnectionQualityChanged = 'connectionQualityChanged',
  TrackUnpublished = 'trackUnpublished',
  TrackPublished = 'trackPublished',
  TrackSubscribed = 'trackSubscribed',
  TrackUnsubscribed = 'trackUnsubscribed',
  // Connected = 'connected',
  // Disconnected = 'disconnected',
  // Resuming = 'resuming',
  // Resumed = 'resumed',
  // Restarting = 'restarting',
  // Restarted = 'restarted',
  // SignalResumed = 'signalResumed',
  // MediaTrackAdded = 'mediaTrackAdded',
  // ActiveSpeakersUpdate = 'activeSpeakersUpdate',
  // DataPacketReceived = 'dataPacketReceived',
}

export enum PeerConnectionState {
  Disconnected = 'disconnected',
  Connecting = 'connecting',
  Connected = 'connected',
  Failed = 'failed',
  New = 'new',
  Closed = 'closed',
}
