import { contextBridge } from 'electron';

import { realmPreload } from '../os/realm.service';
import { authPreload } from '../os/services/auth/auth.service';
import { onboardingPreload } from '../os/services/auth/onboarding.service';
import { migrationPreload } from '../os/services/migration/migration.service';
import { chatPreload } from '../os/services/ship/chat/chat.service';
import { friendsPreload } from '../os/services/ship/friends.service';
import { lexiconPreload } from '../os/services/ship/lexicon.service';
import { notifPreload } from '../os/services/ship/notifications/notifications.service';
import { settingsPreload } from '../os/services/ship/settings.service';
import { shipPreload } from '../os/services/ship/ship.service';
import { bazaarPreload } from '../os/services/ship/spaces/bazaar.service';
import { spacesPreload } from '../os/services/ship/spaces/spaces.service';
import { appPublishersDBPreload } from '../os/services/ship/spaces/tables/appPublishers.table';
import { appRecentsPreload } from '../os/services/ship/spaces/tables/appRecents.table';
import { trovePreload } from '../os/services/ship/trove.service';
import { walletPreload } from '../os/services/ship/wallet/wallet.service';

contextBridge.exposeInMainWorld('realm', realmPreload);
contextBridge.exposeInMainWorld('shipService', shipPreload);
contextBridge.exposeInMainWorld('spacesService', spacesPreload);
contextBridge.exposeInMainWorld('authService', authPreload);
contextBridge.exposeInMainWorld('migrationService', migrationPreload);
contextBridge.exposeInMainWorld('chatService', chatPreload);
contextBridge.exposeInMainWorld('walletService', walletPreload);
contextBridge.exposeInMainWorld('notifService', notifPreload);
contextBridge.exposeInMainWorld('friendDb', friendsPreload);
contextBridge.exposeInMainWorld('bazaarService', bazaarPreload);
contextBridge.exposeInMainWorld('onboardingService', onboardingPreload);
contextBridge.exposeInMainWorld('appInstallService', appPublishersDBPreload);
contextBridge.exposeInMainWorld('appRecentsService', appRecentsPreload);
contextBridge.exposeInMainWorld('settingsService', settingsPreload);
contextBridge.exposeInMainWorld('lexiconService', lexiconPreload);
contextBridge.exposeInMainWorld('troveService', trovePreload);
