name: Auto Author Assign

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Author Assign
        uses: toshimaru/auto-author-assign@v1.6.2
        with:
          repo-token: ${{ secrets.GH_TOKEN }}


