name: Cypress Tests
on:
  pull_request:
    paths:
      - 'hosting-holium-com/**/*.js'
      - 'hosting-holium-com/**/*.ts'
      - 'hosting-holium-com/**/*.tsx'
      - 'hosting-holium-com/**/*.jsx'

env:
  NODE_ENV: development
  API_URL: 'https://backend-server-test.plymouth.network'
  API_HEADERS_VERSION: '2'
  API_HEADERS_CLIENT_ID: '5'
  STRIPE_KEY: 'pk_test_51LIclKGa9esKD8bTeH2WlTZ8ZyJiwXfc5M6e1RdV01zH8G5x3kq0EZbN9Zuhtkm6WBXslp6MQlErpP8lkKtwSMqf00NomWTPxM'
  AMPLITUDE_API_KEY: '03a37e80acd72a1db6d8212a164db540'
  CONVERTKIT_API_KEY: ''

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: yarn workspace @holium/hosting-holium-com build
          start: yarn workspace @holium/hosting-holium-com start
