name: Cypress Tests
on:
  pull_request:
    paths:
      - 'hosting-holium-com/**/*.js'
      - 'hosting-holium-com/**/*.ts'
      - 'hosting-holium-com/**/*.tsx'
      - 'hosting-holium-com/**/*.jsx'
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: yarn workspace @holium/hosting-holium-com dev
