name: Push to master
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install project dependencies
        run: yarn --frozen-lockfile
      - name: Run ESLint
        run: yarn lint:ci:master
