name: staging-build
run-name: Staging Build - ${{ github.actor }}
on:
  workflow_dispatch:
  push:
    branches:
      - staging
  pull_request:
jobs:
  build-staging:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: "npm"
      - run: npm install -g yarn
      - run: yarn install
      - name: "Print token"
        run: echo ${GH_TOKEN}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      # in this branch, set DEBUG_PROD=true to ensure invite code, developer tools,
      #   and other utilities/functionality are available in the final product
      - name: "Build and publish..."
        run: npx cross-env GH_TOKEN="$GH_TOKEN" DEBUG_PROD=true yarn package:publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
