name: staging-build
run-name: Staging Build - ${{ github.actor }}
on:
  workflow_dispatch:
  push:
    branches:
      - staging
  pull_request:
jobs:
  install-node:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: "npm"
      - run: npm install -g yarn
      - run: yarn install
      # in this branch, set DEBUG_PROD=true to ensure invite code, developer tools,
      #   and other utilities/functionality are available in the final product
      - name: "Publishing..."
        run: npx cross-env GH_TOKEN=$GH_TOKEN DEBUG_PROD=true yarn package:publish
        env:
          GH_TOKEN: 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
