export enum PeerEvent {
  Connected = 'connected',
  Disconnected = 'disconnected',
  Failed = 'failed',
  New = 'new',
  Close = 'closed',
  Dialing = 'dialing',
  Redialing = 'redialing',
  MediaStreamAdded = 'mediaStreamAdded',
  MediaStreamRemoved = 'mediaStreamRemoved',
  AudioTrackAdded = 'audioTrackAdded',
  AudioTrackRemoved = 'audioTrackRemoved',
  VideoTrackAdded = 'videoTrackAdded',
  VideoTrackRemoved = 'videoTrackRemoved',
  AudioPlaybackStarted = 'audioPlaybackStarted',
  AudioPlaybackStopped = 'audioPlaybackStopped',
  AudioPlaybackFailed = 'audioPlaybackFailed',
  IsSpeakingChanged = 'isSpeakingChanged',
  Muted = 'muted',
  Unmuted = 'unmuted',
}
